### ISSUE TITLE
Horizontal and vertical camera movement options

### ISSUE THREAD

**Issue by kmck** [tumblr/data-lasso#12]
Currently, you can zoom with the mouse wheel and rotate the data set by click+dragging. It would be useful to have a way to move up/down and left/right relative to the plot area as well.

It might make sense to constrain movement to one axis at a time by default. For example, dragging left and right would rotate around the Y axis (as it does now), and dragging up and down would move the plot area up and down.

Creating "snap" points for rotation (0°, 45°, 90°, etc.) and translation would also be helpful.

**Comment by sushruta** [comment]
Correct me if I'm wrong but you can move up/down and left/right relative to the plot area by rightclick+dragging.

**Comment by tgilan** [comment]
You are correct, you can pan with right mouse button and rotate with left mouse button. 

The other point that you make @kmck is great, some extra navigation options might be really useful.

- Modifier keys on the rotation:
  - Holding down alt might move you into snap rotation mode - useful for when you really want to view at the graph from perfect positions.
  - Holding down shift will constrain movement to one axis.
- Some 3d editing tools, like 3ds Max, have helper cube, called [View Cube](https://knowledge.autodesk.com/support/3ds-max/learn-explore/caas/CloudHelp/cloudhelp/2015/ENU/3DSMax/files/GUID-F8D9EF38-A2BB-4502-95A7-4897A7F30F21-htm.html), in the corner of the visualization. It mimics the rotation of the graph, but clicking on it's sides helps you to move the camera to this position. It's a neat little thing that might be useful to bring here as well.
